### ISSUE TITLE
[BUG] CommandListener object has no attribute 'sender'

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/radio_collar_tracker_dsp2#8]
```
$ sudo service rctrun status
● rctrun.service - RCT OBC Runner
     Loaded: loaded (/lib/systemd/system/rctrun.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-11-02 20:21:26 PDT; 1min 9s ago
   Main PID: 12965 (rctrun)
      Tasks: 5 (limit: 4516)
     Memory: 21.9M
     CGroup: /system.slice/rctrun.service
             ├─12965 /home/e4e/radio_collar_tracker_dsp2/.venv/bin/python /home/e4e/radio_collar_tracker_dsp2/.venv/bin/rctrun
             └─15171 /usr/bin/uhd_usrp_probe --args="type=b200" --init-only

Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]:   File "/home/e4e/radio_collar_tracker_dsp2/.venv/lib/python3.8/site-packages/autostart/rctrun.py", line 125, in initComms
Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]:     self.cmdListener = CommandListener(self.UIB_Singleton, self.tcpport)
Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]:   File "/home/e4e/radio_collar_tracker_dsp2/.venv/lib/python3.8/site-packages/autostart/tcp_command.py", line 183, in __init__
Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]:     self.sock = RCTTCPServer(port)
Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]: TypeError: __init__() missing 1 required positional argument: 'connectionHandler'
Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]: Exception ignored in: <function CommandListener.__del__ at 0x7f6ceef851f0>
Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]: Traceback (most recent call last):
Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]:   File "/home/e4e/radio_collar_tracker_dsp2/.venv/lib/python3.8/site-packages/autostart/tcp_command.py", line 209, in __del__
Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]:     self.sender.join()
Nov 02 20:21:27 e4e-upcore-tci rctrun[12965]: AttributeError: 'CommandListener' object has no attribute 'sender'
```

```
$ python -m pip freeze
attrs==22.1.0
exceptiongroup==1.0.0
iniconfig==1.1.1
packaging==21.3
pluggy==1.0.0
pyparsing==3.0.9
pyserial==3.5
pytest==7.2.0
PyYAML==6.0
radio-collar-tracker-dsp2==0.0.0.3
RCTComms==0.0.0
tomli==2.0.1
```

radio_collar_tracker_dsp2: c7279792
radio_collar_tracker_comms: 02ffc06b

**Comment by ntlhui** [comment]
Fixed
